services:
  - type: web
    name: markgit-editor
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PRODUCTION
        value: "true"
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: markgit-redis
          
  - type: redis
    name: markgit-redis
    plan: free
